import Button from './Button';

import COLOR from './COLOR';

const theme = {
    ...COLOR,
    PRIMARY: COLOR.YELLOW,
    PRIMARY_HOVER: COLOR.YELLOW_DARK,

    PRIMARY_BG: COLOR.YELLOW,
    PRIMARY_STRONG_TEXT: COLOR.YELLOW_DARKER,
    PRIMARY_LIGHT_TEXT: COLOR.YELLOW_DARK,

    SECONDARY: COLOR.GREEN,
    SECONDARY_HOVER: COLOR.GREEN_DARK,
    BACKGROUND: COLOR.WHITE,
};

export {
    theme,
    Button
};
